name: create pre-relase branch

on:
  workflow_dispatch:
  
jobs: 
  run-instrumented-tests:
    runs-on: macos-latest
    
    
    steps:
      - name: setup java11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
    
      - name: checkout
        uses: actions/checkout@v3
        
      - name: create secrets
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: echo CLIENT_ID="$CLIENT_ID" > ./local.properties
      
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

