name: detekt

on:
  push:
    branches: [ dev ]

jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.21.0
         with:
          args: --fail-fast --config ./config/detekt/config.yml
