name: release version

on:
  workflow_dispatch:
  
jobs: 
  release_version:
    runs-on: macos-latest
    
    steps:
      - name: setup java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          
      - name: merge changes
        shell: bash
        run: |
          git pull origin ${{ github.REF_NAME }}
          
      - name: decode Keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'android-keystore.jks'
          fileDir: './app/'
          encodedString: ${{ secrets.ANDROID_KEYSTORE }}
          
      - name: replace version code
        run: newLine=$(awk -v FS="yal_application_version_code = " 'NF>1{print $2 + 1}' ./app/build.gradle); sed -E -i '' -e "s/yal_application_version_code = [[:digit:]]+/yal_application_version_code = $newLine/" ./app/build.gradle
        
      - name: commit update version code
        shell: bash
        run: |
          git add .
          git commit -m 'Updated version code'
          
      - name: create secrets
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: echo CLIENT_ID="$CLIENT_ID" > ./local.properties
          
      - name: build prod bundle
        run: |
          ./gradlew app:bundleRelease
          ./gradlew app:assembleRelease
        env:
          YAL_SIGNING_KEY_ALIAS: ${{ secrets.YAL_SIGNING_KEY_ALIAS }}
          YAL_SIGNING_KEY_PASSWORD: ${{ secrets.YAL_SIGNING_KEY_PASSWORD }}
          YAL_SIGNING_STORE_PASSWORD: ${{ secrets.YAL_SIGNING_STORE_PASSWORD }}
          
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: app/build/outputs/bundle/release/*
          
      - name: push back
        run: |
          git push origin master
          git push origin --delete ${{ github.REF_NAME }}
          git fetch -p
          git checkout dev
          git merge master --allow-unrelated-histories
          git push origin dev
