name: release version

on:
  workflow_dispatch:
  
jobs: 
  release_version:
    runs-on: macos-latest
    
    steps:
      - name: setup java11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
    
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master
      
      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: './app/android-keystore.jks'
          encodedString: ${{ secrets.ANDROID_KEYSTORE }}
          
      - name: merge changes
        shell: bash
        run: |
          git merge ${{ env.GITHUB_REF_NAME }} --ff
          
      - name: replace version code
        shell: bash
        run: |
          newLine=$(awk -v FS="yal_application_version_code = " 'NF>1{print $2 + 1}' ./app/build.gradle); sed -E -i '' -e "s/yal_application_version_code = [[:digit:]]+/yal_application_version_code = $newLine/" ./app/build.gradle
          echo "::set-output name=TAG_NAME::$(awk -v FS="yal_application_version_code = " 'NF>1{print $2 + 1}' ./app/build.gradle)"
      - name: commit update version code
        shell: bash
        run: |
          git add .
          git commit -m 'Updated version code'
          
      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          YAL_SIGNING_STORE_PASSWORD: ${{ secrets.YAL_SIGNING_STORE_PASSWORD }}
          YAL_SIGNING_KEY_ALIAS: ${{ secrets.YAL_SIGNING_KEY_ALIAS }}
          YAL_SIGNING_KEY_PASSWORD: ${{ secrets.YAL_SIGNING_KEY_PASSWORD }}
        
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: app/build/outputs/bundle/release/
